package com.pogreb.design.theme

import androidx.compose.ui.graphics.Color

data class CustomColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceTint: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,

    val bgTertiary: Color,
    val bgDisable: Color,
    val fontDisable: Color,
    val indicatorPositive: Color,
    val indicatorAttention: Color,
    val iconPrimary: Color,
    val iconSecondary: Color,
    val iconDisable: Color,
    val iconPrimaryInvert: Color
)

val LightCustomColorScheme = CustomColorScheme(
    primary = PermanentPrimary,
    onPrimary = FontDayPrimary,
    primaryContainer = PermanentPrimaryLight,
    onPrimaryContainer = FontDayPrimary,
    inversePrimary = PermanentPrimaryDark,
    secondary = PermanentPrimaryDark,
    onSecondary = FontDayPrimary,
    secondaryContainer = PermanentPrimaryLight,
    onSecondaryContainer = FontDayPrimary,
    tertiary = PermanentPrimary,
    onTertiary = FontDayPrimary,
    tertiaryContainer = PermanentPrimaryLight,
    onTertiaryContainer = FontDayPrimary,
    background = BgDayPrimary,
    onBackground = FontDayPrimary,
    surface = BgDayPrimary,
    onSurface = FontDayPrimary,
    surfaceVariant = BgDaySecondary,
    onSurfaceVariant = FontDaySecondary,
    surfaceTint = PermanentPrimary,
    inverseSurface = BgDayInvert,
    inverseOnSurface = FontDayPrimaryInvert,
    error = IndicatorDayError,
    onError = FontDayPrimaryInvert,
    errorContainer = IndicatorDayError,
    onErrorContainer = FontDayPrimaryInvert,
    outline = BorderDayPrimary,
    outlineVariant = BorderDaySecondary,
    scrim = Color.Black.copy(alpha = 0.5f),

    bgTertiary = BgDayTertiary,
    bgDisable = BgDayDisable,
    fontDisable = FontDayDisable,
    indicatorPositive = IndicatorDayPositive,
    indicatorAttention = IndicatorDayAttention,
    iconPrimary = IconDayPrimary,
    iconSecondary = IconDaySecondary,
    iconDisable = IconDayDisable,
    iconPrimaryInvert = IconDayPrimaryInvert
)

val DarkCustomColorScheme = CustomColorScheme(
    primary = PermanentPrimary,
    onPrimary = FontNightPrimary,
    primaryContainer = PermanentPrimaryLight,
    onPrimaryContainer = FontNightPrimary,
    inversePrimary = FontNightPrimary,
    secondary = PermanentPrimaryDark,
    onSecondary = FontNightPrimary,
    secondaryContainer = PermanentPrimaryLight,
    onSecondaryContainer = FontNightPrimary,
    tertiary = PermanentPrimary,
    onTertiary = FontNightPrimary,
    tertiaryContainer = PermanentPrimaryLight,
    onTertiaryContainer = FontNightPrimary,
    background = BgNightPrimary,
    onBackground = FontNightPrimary,
    surface = BgNightPrimary,
    onSurface = FontNightPrimary,
    surfaceVariant = BgNightSecondary,
    onSurfaceVariant = FontNightSecondary,
    surfaceTint = PermanentPrimary,
    inverseSurface = BgNightInvert,
    inverseOnSurface = FontNightPrimaryInvert,
    error = IndicatorNightError,
    onError = FontNightPrimaryInvert,
    errorContainer = IndicatorNightError,
    onErrorContainer = FontNightPrimaryInvert,
    outline = BorderNightPrimary,
    outlineVariant = BorderNightSecondary,
    scrim = Color.Black.copy(alpha = 0.5f),

    bgTertiary = BgNightTertiary,
    bgDisable = BgNightDisable,
    fontDisable = FontNightDisable,
    indicatorPositive = IndicatorNightPositive,
    indicatorAttention = IndicatorNightAttention,
    iconPrimary = IconNightPrimary,
    iconSecondary = IconNightSecondary,
    iconDisable = IconNightDisable,
    iconPrimaryInvert = IconNightPrimaryInvert
)